workflows:
    ios-workflow:
      name: ios_workflow
      instance_type: mac_mini_m1
      integrations:
        app_store_connect: CM_NEVERCODE
      environment:
        vars:
          XCODE_WORKSPACE: "CM-NATIVE-IOS.xcodeproj" # <-- Put the name of your workspace here.
          # XCODE_PROJECT: "native_ios_app.xcodeproj"
#           XCODE_SCHEME: "native_ios_app" # <-- Put the name of your scheme here.
          BUNDLE_ID: "io.codemagic.mars.CM-NATIVE-IOS" # <-- Put your Bundle Id here.
          XCODE_SCHEME: "CM-NATIVE-IOS" # <-- Put the name of your scheme here.
        xcode: 15.0
        ios_signing:
            distribution_type: app_store # or: ad_hoc | development | enterprise
            bundle_identifier: io.codemagic.mars.CM-NATIVE-IOS
      
      scripts:

        - name: Pod inst
          script: |
              echo $NPM_RC
              pod install
#         - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
#           script: |
#             keychain initialize
# #      until docker system info > /dev/null 2>&1; do sleep 1; done
#         - name: Fetch signing files
#           script: |
#             app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
#             app-store-connect fetch-signing-files com.mars.native-ios-appUITests.xctrunner --type IOS_APP_STORE --create
        # - name: Use system default keychain
        #   script: |
        #     keychain add-certificates
        - name: Set up code signing settings on Xcode project
          script: |
             xcode-project use-profiles
        
        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

      artifacts:
        - build/ios/ipa/*.ipa
#         - build/ios/ipa/bullet.ipa
        - /tmp/xcodebuild_logs/*.log
#         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
#         - /Users/builder/clone/build/ios_integ/Build/Products/ios_tests.zip
      publishing:
        app_store_connect:
          auth: integration