on: push
    
jobs:
  services_job:
    name: integration-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Trigger Codemagic build
        uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v2.0.0
        with:
          app-id: 656a0292cc50c7a8cd27a1f2
          workflow-id: cm.workflow
          branch: "main"
          token: ${{ secrets.CODEMAGIC_TOKEN }}
